---
version: '3.9'

services:

  frontend:
    image: ${IMAGE_NAME_PREFIX}-frontend:${IMAGE_TAG:-latest}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://${STACK_NAME-2025-pythoncerrado-org}_backend:8080/Plone
      RAZZLE_API_PATH: https://${STACK_HOSTNAME-2025.pythoncerrado.org}
      RAZZLE_MATOMO_SITE_ID: 5
      RAZZLE_MATOMO_URL: https://stats.pythoncerrado.org.br/
    networks:
      - public
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == app
          - node.labels.env == production
          - node.labels.generation == v2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=public"
        # Service
        - "traefik.http.services.svc-${STACK_PREFIX}-frontend.loadbalancer.server.port=3000"
        # Routers
        ## / (Internal)
        - "traefik.http.routers.rt-${STACK_PREFIX}-frontend.rule=Host(`${STACK_HOSTNAME-2025.pythoncerrado.org}`)"
        - "traefik.http.routers.rt-${STACK_PREFIX}-frontend.entrypoints=https"
        - "traefik.http.routers.rt-${STACK_PREFIX}-frontend.tls=true"
        - "traefik.http.routers.rt-${STACK_PREFIX}-frontend.tls.certresolver=${CERTRESOLVER-le-tls}"
        - "traefik.http.routers.rt-${STACK_PREFIX}-frontend.service=svc-${STACK_PREFIX}-frontend"

  backend:
    image: ${IMAGE_NAME_PREFIX}-backend:${IMAGE_TAG:-latest}
    environment:
      ZEO_ADDRESS: ${STACK_NAME-2025-pythoncerrado-org}_db:8100
    networks:
      - public
      - nw-internal
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == app
          - node.labels.env == production
          - node.labels.generation == v2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=public"
        # Services
        - "traefik.http.services.svc-${STACK_PREFIX}-backend.loadbalancer.server.port=8080"
        # Middlewares
        ## VHM rewrite /++api++/
        - "traefik.http.middlewares.mw-${STACK_PREFIX}-backend-vhm-api.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.mw-${STACK_PREFIX}-backend-vhm-api.replacepathregex.replacement=/VirtualHostBase/https/${STACK_HOSTNAME-2025.pythoncerrado.org}/Plone/++api++/VirtualHostRoot$$1"
        ## VHM rewrite /ClassicUI/
        - "traefik.http.middlewares.mw-${STACK_PREFIX}-backend-vhm-classic.replacepathregex.regex=^/ClassicUI($$|/.*)"
        - "traefik.http.middlewares.mw-${STACK_PREFIX}-backend-vhm-classic.replacepathregex.replacement=/VirtualHostBase/https/${STACK_HOSTNAME-2025.pythoncerrado.org}/Plone/VirtualHostRoot/_vh_ClassicUI$$1"
        ## Basic Authentication
        ### Note: all dollar signs in the hash need to be doubled for escaping.
        ### To create user:password pair, it's possible to use this command:
        ### echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
        ### Defaults to admin:admin
        - "traefik.http.middlewares.mw-${STACK_PREFIX}-backend-auth.basicauth.users=pycerrado25:$$apr1$$MB3D/hZW$$aRvCsyfwTHeo5KUox4EeY0"

        # Routes
        ## /++api++
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-api.rule=Host(`${STACK_HOSTNAME-2025.pythoncerrado.org}`) && PathPrefix(`/++api++`)"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-api.entrypoints=https"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-api.tls=true"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-api.service=svc-${STACK_PREFIX}-backend"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-api.middlewares=mw-${STACK_PREFIX}-backend-vhm-api"
        ## /ClassicUI
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-classic.rule=Host(`${STACK_HOSTNAME-2025.pythoncerrado.org}`) && PathPrefix(`/ClassicUI`)"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-classic.entrypoints=https"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-classic.tls=true"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-classic.service=svc-${STACK_PREFIX}-backend"
        - "traefik.http.routers.rt-${STACK_PREFIX}-backend-classic.middlewares=gzip,mw-${STACK_PREFIX}-backend-auth,mw-${STACK_PREFIX}-backend-vhm-classic"

  db:
    image: plone/plone-zeo:5.3.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 1s
        order: stop-first
      placement:
        constraints:
          - node.labels.type == data
          - node.labels.env == production
    volumes:
      - vol-site-data:/data
    networks:
      - nw-internal

networks:
  public:
    external: true
  nw-internal:
    internal: true
    driver: overlay

volumes:
  vol-site-data:
    driver_opts:
      type: none
      device: /srv/pycerrado25-live/data
      o: bind
